baseurl         = "/dicas-bash"
theme           = "hugo-remark-twemoji"
languageCode    = "en-us"
title           = "Dicas Bash"
canonifyurls    = true

[params]
googleAnalytics = ""
name            = "Marco Paganini"
description     = "Dicas Bash (slides)"
custom_css      = ["custom.css"]
